server:
  port: 9090

spring:
#  datasource:
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://116.126.158.6:3306/todo_db?characterEncoding=UTF-8
#      username: todo
#      password: 1234
  datasource:
    url: jdbc:mariadb://localhost:3306/todo_db?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: todo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    defer-datasource-initialization: true
    database: mysql

jwt:
  secret: meteor
  expiration: 1480000
  header: Authorization